# Generated by Django 4.2 on 2026-05-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfil_direccion_perfil_foto_perfil_informe_laboral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='negocio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
